### ISSUE TITLE
Request to add CVPR paper

### ISSUE THREAD

**Issue by prinshul** [amusi/CVPR2021-Papers-with-Code#101]
Please add our Oral **Domain Generalisation** paper, "Generalization on Unseen Domains via Inference-time Label-Preserving Target Projections"

Link: https://openaccess.thecvf.com/content/CVPR2021/papers/Pandey_Generalization_on_Unseen_Domains_via_Inference-Time_Label-Preserving_Target_Projections_CVPR_2021_paper.pdf
arxiv: https://arxiv.org/abs/2103.01134
Source code: https://github.com/VSumanth99/InferenceTimeDG

Thank you.

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
