### ISSUE TITLE
Request for adding a new paper of 3D human pose and shape estimation

### ISSUE THREAD

**Issue by Jeff-sjtu** [amusi/CVPR2021-Papers-with-Code#56]
Title: HybrIK: A Hybrid Analytical-Neural Inverse Kinematics Solution for 3D Human Pose and Shape Estimation
arXiv: https://arxiv.org/abs/2011.14672
Code: https://github.com/Jeff-sjtu/HybrIK
Project Page: https://jeffli.site/HybrIK/

**Comment by Jeff-sjtu** [comment]
Thank you!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
