### ISSUE TITLE
Parser-Free Virtual Try-on Accapted to CVPR 2021

### ISSUE THREAD

**Issue by youweiliang** [amusi/CVPR2021-Papers-with-Code#60]
Hi, please consider adding this paper to your awesome repo: 
Title: Parser-Free Virtual Try-on via Distilling Appearance Flows (基于外观流蒸馏的无需人体解析的虚拟换装) (Accepted to CVPR 2021) [https://arxiv.org/abs/2103.04559](https://arxiv.org/abs/2103.04559) 
GitHub: [https://github.com/geyuying/PF-AFN](https://github.com/geyuying/PF-AFN)
Thank you.

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
