### ISSUE TITLE
A 3D Point Cloud Registration Paper accepcted by CVPR 2021.

### ISSUE THREAD

**Issue by XuyangBai** [amusi/CVPR2021-Papers-with-Code#61]
PointDSC: Robust Point Cloud Registration using Deep Spatial Consistency
Paper: https://arxiv.org/abs/2103.05465
Code: https://github.com/XuyangBai/PointDSC

Thanks a lot : )

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
