### ISSUE TITLE
Three Human Object Interaction papers

### ISSUE THREAD

**Issue by irvingzhang0512** [amusi/CVPR2021-Papers-with-Code#71]
Copied from [HOI-Learning-List](https://github.com/DirtyHarryLYL/HOI-Learning-List)

Title: Query-Based Pairwise Human-Object Interaction Detection with Image-Wide Contextual Information
Paper: https://arxiv.org/abs/2103.05399
Code: https://github.com/hitachi-rd-cv/qpic

Title: Reformulating HOI Detection as Adaptive Set Prediction
Paper: https://arxiv.org/abs/2103.05983
Code: https://github.com/yoyomimi/AS-Net

Title: Detecting Human-Object Interaction via Fabricated Compositional Learning
Paper: https://arxiv.org/abs/2103.08214
Code: https://github.com/zhihou7/FCL

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
