### ISSUE TITLE
Add one accepted paper

### ISSUE THREAD

**Issue by Nicholasli1995** [amusi/CVPR2021-Papers-with-Code#74]
Topic: 3D object detection, 3D pose estimation, vehicle pose estimation
Title: Exploring intermediate representation for monocular vehicle pose estimation
Code: https://github.com/Nicholasli1995/EgoNet

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing

**Comment by Nicholasli1995** [comment]
Link to the paper: https://arxiv.org/abs/2011.08464
