### ISSUE TITLE
Add CVPR2021 paper, Domain Consensus Clustering for Universal Domain Adaptation

### ISSUE THREAD

**Issue by Solacex** [amusi/CVPR2021-Papers-with-Code#76]
Hello, here is the code and paper. 

Paper: http://reler.net/papers/guangrui_cvpr2021.pdf
Code: https://github.com/Solacex/Domain-Consensus-Clustering

Thank you~

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
