### ISSUE TITLE
Add CVPR2021 Paper, Cross-Modal Center Loss for 3D Cross-Modal Retrieval

### ISSUE THREAD

**Issue by LongLong-Jing** [amusi/CVPR2021-Papers-with-Code#78]
Title: Cross-Modal Center Loss for 3D Cross-Modal Retrieval
Paper Link: https://arxiv.org/abs/2008.03561
Code Link: https://github.com/LongLong-Jing/Cross-Modal-Center-Loss

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
