### ISSUE TITLE
Please add our CVPR 2021 paper

### ISSUE THREAD

**Issue by SeanChenxy** [amusi/CVPR2021-Papers-with-Code#83]
Please add our CVPR 2021 paper in 3D human pose: Camera-Space Hand Mesh Recovery via Semantic Aggregation and Adaptive 2D-1D Registration
paper link: https://arxiv.org/abs/2103.02845
Code link: https://github.com/SeanChenxy/HandMesh

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
