### ISSUE TITLE
Please add our CVPR 2021 oral paper

### ISSUE THREAD

**Issue by paul007pl** [amusi/CVPR2021-Papers-with-Code#85]
Variational Relational Point Completion Network

**Comment by paul007pl** [comment]
Code: https://github.com/paul007pl/VRCNet
Project Page: https://paul007pl.github.io/projects/VRCNet

**Comment by paul007pl** [comment]
paper: https://arxiv.org/abs/2104.10154

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
