### ISSUE TITLE
Please include our CVPR 2021 paper on point cloud completion

### ISSUE THREAD

**Issue by junzhezhang** [amusi/CVPR2021-Papers-with-Code#90]
Hi!
Please include our CVPR 2021 paper on point cloud completion.

Title: Unsupervised 3D Shape Completion through GAN Inversion
Project page: https://junzhezhang.github.io/projects/ShapeInversion/ 
code: https://github.com/junzhezhang/shape-inversion
paper: https://arxiv.org/abs/2104.13366 

Thank you!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
