### ISSUE TITLE
Please add our CVPR paper

### ISSUE THREAD

**Issue by zwzhu-d** [amusi/CVPR2021-Papers-with-Code#93]
<a name="Label-Noise"></a>

# 标签噪声(Label-Noise)

**A Second-Order Approach to Learning with Instance-Dependent Label Noise**

- Paper(Oral): https://arxiv.org/abs/2012.11854
- Code: https://github.com/UCSC-REAL/CAL

Thanks!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
