### ISSUE TITLE
Code for our paper "Semi-Supervised Semantic Segmentation with Cross Pseudo Supervision"

### ISSUE THREAD

**Issue by charlesCXK** [amusi/CVPR2021-Papers-with-Code#95]
Hi, thanks for your effort! Please add the official code for the paper "Semi-Supervised Semantic Segmentation with Cross Pseudo Supervision".
https://github.com/charlesCXK/TorchSemiSeg

Thanks very much!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
