### ISSUE TITLE
Rotation Detection

### ISSUE THREAD

**Issue by yangxue0827** [amusi/CVPR2021-Papers-with-Code#96]
paper: Dense Label Encoding for Boundary Discontinuity Free Rotation Detection
link: https://arxiv.org/abs/2011.09670
code: https://github.com/Thinklab-SJTU/DCL_RetinaNet_Tensorflow   or   https://github.com/yangxue0827/RotationDetection

**Comment by yangxue0827** [comment]
paper: ReDet: A Rotation-equivariant Detector for Aerial Object Detection
link: https://arxiv.org/abs/2103.07733
code: https://github.com/csuhan/ReDet

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
