### ISSUE TITLE
Please add our CVPR 2021 paper

### ISSUE THREAD

**Issue by JesseZhang92** [amusi/CVPR2021-Papers-with-Code#99]
Learning to Aggregate and Personalize 3D Face from In-the-Wild Photo Collection
Topic on: 3D Reconstruction, 3D Face, Graphics

arxiv: http://arxiv.org/abs/2106.07852
code: https://github.com/TencentYoutuResearch/3DFaceReconstruction-LAP

Thanks!

**Comment by GabrielMon** [comment]
> Learning to Aggregate and Personalize 3D Face from In-the-Wild Photo Collection
> Topic on: 3D Reconstruction, 3D Face, Graphics
> 
> arxiv: http://arxiv.org/abs/2106.07852
> code: https://github.com/TencentYoutuResearch/3DFaceReconstruction-LAP
> 
> Thanks!

Sorry for writing here,  but I don't know will you get notification for my question, so I'm trying my best to come to your answer. 

Greetings

https://github.com/OniroAI/MonoDepth-PyTorch/issues/15#issuecomment-457618480

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing
